telegram:
  bot_token: AAAAAAA:AAAAAAAAAAAAAAAAAAAAA
  channel_id: -1234567890
  admin_id: 123456789
redis:
  host: 127.0.0.1
  port: 6379
  db: 0
llm:
  ollama:
    llama3.2-vision:
      image_describe_prompt: Describe the objects in the image directly, listing their characteristics (e.g., color, type, material, and position). Avoid introductory or contextual phrases