version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - redis_network
    volumes:
      - redis_data:/data
volumes:
  redis_data:
networks:
  redis_network:
    driver: bridge